--- #YAML:1.0
name:                Catalyst-Model-REST
version:             0.01
abstract:            REST model class for Catalyst
license:             ~
author:              
    - Kaare Rasmussen <kaare@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Catalyst::Model:               0
    HTTP::Request::Common:         0
    JSON::XS:                      0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
