---
abstract: 'REST model class for Catalyst'
author:
  - 'Kaare Rasmussen, <kaare at cpan dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-REST
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Model: 0
  Data::Serializable: 0.40.1
  HTTP::Request::Common: 0
  JSON: 2.12
  JSON::XS: 2.2222
  LWP::UserAgent: 0
  Moose: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kaare/Catalyst-Model-REST.git
version: 0.07
