---
abstract: 'REST model class for Catalyst'
author:
  - 'Kaare Rasmussen <kaare at cpan dot net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-REST
requires:
  Carp: 0
  Catalyst::Model: 0
  Data::Serializable: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Try::Tiny: 0
  perl: 5.010
resources:
  repository: git://github.com/kaare/Catalyst-Model-REST.git
version: 0.10
